name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install -y libncurses5
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r13b
    - uses: actions/checkout@v3
    - run: ./init.sh
    - run: ndk-build -C document-viewer
    - run: |
        keytool -genkey -v -keystore ~/keystore -storepass password -keypass password -alias alias -keyalg RSA -validity 100000 -dname "CN=Android"
        mkdir -p ~/.gradle/
        echo "signingStoreLocation=/home/runner/keystore" > ~/.gradle/gradle.properties
        echo "signingStorePassword=password" >> ~/.gradle/gradle.properties
        echo "signingKeyAlias=alias" >> ~/.gradle/gradle.properties
        echo "signingKeyPassword=password" >> ~/.gradle/gradle.properties
    - run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: document-viewer/build/outputs/apk/release
